const elements = [
  {
    tag: "header",
    id: "main-header",
    children: [
      {
        tag: "div",
        class: "header-content",
        children: [
          {
            tag: "h1",
            text: "Welcome to the Form Generated by JS",
          },
        ],
      },
    ],
  },
  {
    tag: "main",
    id: "main-content",
    children: [
      {
        tag: "div",
        class: "form-container",
        children: [
          {
            tag: "form",
            id: "user-form",
            attributes: { action: "#" },
            children: [
              {
                tag: "div",
                class: "user-form-inputs",
                children: [
                  {
                    tag: "div",
                    children: [
                      {
                        tag: "label",
                        attributes: { for: "first-name" },
                        text: "First Name:",
                      },
                      {
                        tag: "input",
                        attributes: {
                          type: "text",
                          id: "first-name",
                          name: "first-name",
                        },
                      },
                    ],
                  },
                  {
                    tag: "div",
                    children: [
                      {
                        tag: "label",
                        attributes: { for: "last-name" },
                        text: "Last Name:",
                      },
                      {
                        tag: "input",
                        attributes: {
                          type: "text",
                          id: "last-name",
                          name: "last-name",
                        },
                      },
                    ],
                  },
                  {
                    tag: "div",
                    children: [
                      {
                        tag: "label",
                        attributes: { for: "age" },
                        text: "Age:",
                      },
                      {
                        tag: "input",
                        attributes: { type: "number", id: "age", name: "age" },
                      },
                    ],
                  },
                  {
                    tag: "div",
                    children: [
                      {
                        tag: "label",
                        attributes: { for: "gender" },
                        text: "Gender:",
                      },
                      {
                        tag: "select",
                        attributes: { id: "gender", name: "gender" },
                        children: [
                          {
                            tag: "option",
                            attributes: { value: "male" },
                            text: "Male",
                          },
                          {
                            tag: "option",
                            attributes: { value: "female" },
                            text: "Female",
                          },
                          {
                            tag: "option",
                            attributes: { value: "other" },
                            text: "Other",
                          },
                        ],
                      },
                    ],
                  },
                  {
                    tag: "div",
                    children: [
                      {
                        tag: "label",
                        attributes: { for: "email" },
                        text: "Email:",
                      },
                      {
                        tag: "input",
                        attributes: {
                          type: "email",
                          id: "email",
                          name: "email",
                        },
                      },
                    ],
                  },
                  {
                    tag: "div",
                    children: [
                      {
                        tag: "label",
                        attributes: { for: "phone" },
                        text: "Phone Number:",
                      },
                      {
                        tag: "input",
                        attributes: { type: "tel", id: "phone", name: "phone" },
                      },
                    ],
                  },
                ],
              },
              {
                tag: "div",
                class: "user-form-button",
                children: [
                  {
                    tag: "button",
                    attributes: { type: "submit" },
                    text: "Submit",
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
];

const styles = [
  // {
  //   selector: "*",
  //   style: {
  //     padding: "0",
  //     margin: "0",
  //     boxSizing: "border-box",
  //   },
  // },
  // {
  //   selector: "#main-header",
  //   style: {
  //     backgroundColor: "green",
  //     color: "white",
  //     padding: "20px",
  //     textAlign: "center",
  //   },
  // },
  // {
  //   selector: ".header-content",
  //   style: {
  //     margin: "10px",
  //   },
  // },
  // {
  //   selector: "#main-header h1",
  //   style: {
  //     fontFamily: "'Arial', sans-serif",
  //     fontSize: "2.5em",
  //   },
  // },
  // {
  //   selector: "#main-content",
  //   style: {
  //     display: "flex",
  //     alignItems: "center",
  //     marginTop: "50px",
  //     padding: "20px",
  //     backgroundColor: "#fff",
  //   },
  // },
  // {
  //   selector: ".form-container",
  //   style: {
  //     maxWidth: "800px",
  //     margin: "0 auto",
  //     padding: "20px",
  //     backgroundColor: "#efefef",
  //   },
  // },
  // {
  //   selector: "#user-form",
  //   style: {
  //     display: "flex",
  //     flexDirection: "column",
  //     gap: "20px",
  //   },
  // },
  // {
  //   selector: ".user-form-inputs",
  //   style: {
  //     display: "flex",
  //     flexWrap: "wrap",
  //     gap: "20px",
  //   },
  // },
  // {
  //   selector: ".user-form-inputs > div",
  //   style: {
  //     flexGrow: "1",
  //     flexShrink: "1",
  //     flexBasis: "calc(40%)",
  //     display: "flex",
  //     flexDirection: "column",
  //   },
  // },
  // {
  //   selector: ".user-form-inputs > div > select",
  //   style: {
  //     padding: "9px",
  //     border: "1px solid #000",
  //     borderRadius: "5px",
  //   },
  // },
  // {
  //   selector: ".user-form-inputs label",
  //   style: {
  //     marginBottom: "5px",
  //     fontWeight: "bold",
  //   },
  // },
  // {
  //   selector: ".user-form-inputs input",
  //   style: {
  //     padding: "10px",
  //     border: "1px solid #000",
  //     borderRadius: "5px",
  //   },
  // },
  // {
  //   selector: ".user-form-button",
  //   style: {
  //     width: "50%",
  //     margin: "0 auto",
  //   },
  // },
  // {
  //   selector: ".user-form-button button",
  //   style: {
  //     width: "100%",
  //     padding: "10px 20px",
  //     backgroundColor: "green",
  //     color: "white",
  //     border: "none",
  //     borderRadius: "5px",
  //     cursor: "pointer",
  //   },
  // },
  // {
  //   selector: ".user-form-button button:hover",
  //   style: {
  //     backgroundColor: "darkgreen",
  //   },
  // },
];

function createHtmlPage(elements) {
  const arr = [];
  elements.forEach((element) => {
    const tag = document.createElement(element.tag);
    if (element.class) {
      tag.classList.add(`${element.class}`);
    }
    tag.textContent = element.text;
    addingStyle(element, tag);
    if (element.children) {
      const childArr = createHtmlPage(element.children);
      childArr.forEach((childTag) => {
        tag.appendChild(childTag);
      });
    }
    for (const i in element) {
      if (
        !(
          i === "tag" ||
          i === "class" ||
          i === "text" ||
          i === "children" ||
          i === "style"
        )
      ) {
        tag.setAttribute(`${i}`, `${element[i]}`);
      }
    }
    arr.push(tag);
  });
  return arr;
}

function addingStyle(element, tag) {
  for (const style in element.style) {
    tag.style[style] = element.style[style];
  }
}

const arr = createHtmlPage(elements);

arr.forEach((tag) => {
  document.body.appendChild(tag);
});

cssForHtmlPage(styles);

function cssForHtmlPage(styles) {
  styles.forEach((style) => {
    const tagArr = document.querySelectorAll(`${style.selector}`);
    tagArr.forEach((tag) => {
      addingStyle(style, tag);
    });
  });
}

//----------------------------demo html json format--------------------------------------------
// {
//     tag: "div",
//     class: "container",
//     style: {
//         border: "1px solid black",
//         padding: "10px",
//     },
//     children: [
//         {
//             tag: "h1",
//             class: "heading",
//             style: {
//                 color: "blue",
//                 fontSize: "24px"
//             },
//             text: "Hello World",
//         },
//         {
//             tag: "p",
//             style: {
//                 fontSize: "50px"
//             },
//             text: "Array of Objects",
//         },
//     ],
// },

//-------------------demo css json format----------------------------------------
// {
//   selector: ".container",
//   style: {
//     border: "1px solid black",
//     padding: "10px",
//   },
// },
// {
//   selector: ".heading",
//   style: {
//     color: "blue",
//     fontSize: "24px",
//   },
// },
// {
//   selector: "p",
//   style: {
//     fontSize: "50px",
//   },
// },
// {
//   selector: ".container>p",
//   style: {
//     fontSize: "50px",
//   },
// },
